### ISSUE TITLE
Display List of Events in Todo Sidebar

### ISSUE THREAD

**Issue by nehpethP** [Software-Engineering-Group-9/Front-End#8]
need help displaying created events in the todo list sidebar. also need help setting up communication with the backend

**Comment by BoKlassen** [comment]
eventList exists already addEvent() function. We need to convert eventList into HTML Unordered List and display in sidebar.

**Comment by nehpethP** [comment]
branch stephen contains stylized test card for todo list item, does not contain actual event details

**Comment by nehpethP** [comment]
master branch contains the newest version that shows the created event and all its details in the todo list.

**Comment by MingHaoC** [comment]
Do we still need help with this? why was it reopen?

**Comment by nehpethP** [comment]
brandon closed it thinking it was done
at the moment we can now add multiple events into the todo list but we still need communication between the front and back end as well as actually displaying those events into the calendar

**Comment by BoKlassen** [comment]
The sidebar currently scrolls vertically, but only once the events are off the screen. Can we fix this? Probably something to do with the div height.

**Comment by nehpethP** [comment]
this works now
